### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by swilliamson7** [Argonne-National-Laboratory/Checkpointing.jl#38]
Apologies in advance if this isn't the right place to put this! I wanted to ask if some minor features could be added. Specifically: 

1. The ability to write every Nth checkpoint rather than every single one. I pretty quickly run out of computer space when I write every checkpoint (i.e. > 400gb of stuff...)
2. Could we maybe output the checkpoints as a .nc file rather than .h5? This is less crucial than (1), but could still be nice. I went back to try and make videos with some past h5 files and found reading them tricky

**Comment by michel2323** [comment]
https://github.com/Argonne-National-Laboratory/Checkpointing.jl/pull/40
